[package]
name = "raccoon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "raccoonc"
path = "src/bin/raccoonc.rs"

[dependencies]
clap = { version = "3.1.0", features = ["derive"] }

[workspace]
members = [
	'compiler',
	'macros/*',
	'proptests'
]

[profile.dev]
split-debuginfo = "unpacked"
